import Head from "next/head";
import Swal from "sweetalert2";
import { signIn } from "next-auth/react";
import styles from "./Login.module.scss";
import { useRouter } from "next/router";
import { useState } from "react";

export default function LoginView() {
  const { push, query } = useRouter();
  const [submitData, setSubmitData] = useState(false);
  const [error, setError] = useState("");
  const callbackUrl: any = query.callbackUrl || "/dashboard";

  const handleSubmit = async (e: any) => {
    setSubmitData(true);
    setError("");
    e.preventDefault();

    try {
      const res = await signIn("credentials", {
        redirect: false,
        email: e.target.email.value,
        password: e.target.password.value,
        callbackUrl,
      });

      if (!res?.error) {
        setSubmitData(false);
        Swal.fire({
          icon: "success",
          title: "Login success 🎉",
          showConfirmButton: false,
          timer: 1500,
        });
        push(callbackUrl);
      } else {
        setError(res.error);
        Swal.fire({
          icon: "error",
          title: "Error ⛔️",
          text: res.error,
          confirmButtonText: "Oke",
        });
        setSubmitData(false);
      }
    } catch (error: any) {
      setError(error);
      Swal.fire({
        icon: "error",
        title: "Error ⛔️",
        text: error,
        confirmButtonText: "Oke",
      });
      setSubmitData(false);
    }
  };

  return (
    <>
      <Head>
        <title>Telyutizen | Login </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="row vh-100 d-flex align-items-center justify-content-center">
          <div className="col-md-4">
            {error && (
              <div className="alert alert-danger rounded-4">{error}</div>
            )}
            <aside className={`rounded-4 shadow-sm px-3 p-3 ${styles.blur}`}>
              <h2>Login 📨</h2>
              <p>Silahkan masuk dengan akun terlebih dahulu</p>
              <div className="alert alert-info rounded-4">
                <p>Informasi akun demo:</p>
                <ul>
                  <li>Email: telyutizen@gmail.com</li>
                  <li>Password: 12345678</li>
                </ul>
              </div>
              <form onSubmit={handleSubmit}>
                <input
                  className={`w-100 rounded-pill shadow-sm mb-2 p-2 text-black ${styles.blur}`}
                  type="email"
                  id="email"
                  name="email"
                  placeholder="Email"
                  disabled={submitData}
                />
                <input
                  className={`w-100 rounded-pill shadow-sm mb-2 p-2 text-black  ${styles.blur}`}
                  type="text"
                  id="password"
                  name="password"
                  placeholder="Password"
                  disabled={submitData}
                />
                <button
                  className={`w-100 border border-0 rounded-pill shadow-sm px-4 py-2 text-white ${styles.btn__primary}`}
                  type="submit"
                  disabled={submitData}
                >
                  {submitData ? (
                    <>
                      <span
                        className="spinner-border spinner-border-sm"
                        role="status"
                        aria-hidden="true"
                      ></span>
                      <span className="sr-only mr-3">Mencoba Login ...</span>
                    </>
                  ) : (
                    <>Masuk ke Akun ✅</>
                  )}
                </button>
              </form>
            </aside>
          </div>
        </div>
      </div>
    </>
  );
}
